<?php
declare(strict_types=1);
function handle_profile_route(string $method,string $path):bool{if($path!=='/profile'&&strpos($path,'/profile/')!==0)return false;if($path==='/profile'){if($method==='GET'){profile_get();return true;}if($method==='PUT'){profile_update();return true;}method_not_allowed(['GET','PUT']);}if($path==='/profile/sync'){if($method!=='POST')method_not_allowed(['POST']);profile_sync();return true;}if($path==='/profile/career-fit'){if($method!=='GET')method_not_allowed(['GET']);profile_career_fit();return true;}if($path==='/profile/cognitive-report'){if($method!=='GET')method_not_allowed(['GET']);profile_cognitive_report();return true;}error_response('NOT_FOUND','مسیر پروفایل پیدا نشد.',404);return true;}
function current_profile_payload(PDO $pdo,array $a):array{$u=fetch_user_by_id($pdo,(int)$a['user']['id']);$s=load_profile_state($pdo,(int)$a['user']['id']);return build_user_profile($u,$s);}
function profile_get():void{$pdo=Database::pdo();$a=require_auth();success_response(current_profile_payload($pdo,$a));}
function profile_update():void{$pdo=Database::pdo();$a=require_auth();$d=read_json_body();reject_unknown_keys($d,['name','role'],'به‌روزرسانی پروفایل');$fields=[];$params=[];if(array_key_exists('name',$d)){$name=clean_string($d['name'],120);if($name==='')error_response('VALIDATION_ERROR','نام نمی‌تواند خالی باشد.',422);$fields[]='name=?';$params[]=$name;}if(array_key_exists('role',$d)){$role=clean_string($d['role'],120);if($role==='')error_response('VALIDATION_ERROR','نقش نمی‌تواند خالی باشد.',422);$fields[]='role=?';$params[]=$role;}if($fields){$params[]=(int)$a['user']['id'];$pdo->prepare('UPDATE users SET '.implode(',',$fields).',updated_at=NOW() WHERE id=?')->execute($params);}$u=fetch_user_by_id($pdo,(int)$a['user']['id']);$s=load_profile_state($pdo,(int)$a['user']['id']);success_response(build_user_profile($u,$s));}
function profile_sync():void{$pdo=Database::pdo();$a=require_auth();$d=read_json_body();if(isset($d['profile']))reject_unknown_keys($d,['profile'],'همگام‌سازی پروفایل');$in=(isset($d['profile'])&&is_array($d['profile']))?$d['profile']:$d;$pdo->beginTransaction();try{$updates=[];$params=[];if(array_key_exists('name',$in)){ $name=clean_string($in['name'],120); if($name!==''){$updates[]='name=?';$params[]=$name;}}if(array_key_exists('role',$in)){ $role=clean_string($in['role'],120); if($role!==''){$updates[]='role=?';$params[]=$role;}}if($updates){$params[]=(int)$a['user']['id'];$pdo->prepare('UPDATE users SET '.implode(',',$updates).',updated_at=NOW() WHERE id=?')->execute($params);}$s=load_profile_state($pdo,(int)$a['user']['id'],true);if(isset($in['bigFive'])&&is_array($in['bigFive']))$s['big_five']=validate_big_five_scores($in['bigFive']);save_profile_state($pdo,(int)$a['user']['id'],$s);$pdo->commit();$u=fetch_user_by_id($pdo,(int)$a['user']['id']);success_response(build_user_profile($u,$s));}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
function profile_career_fit():void{$pdo=Database::pdo();$a=require_auth();success_response(get_career_fit(current_profile_payload($pdo,$a)));}
function profile_cognitive_report():void{$pdo=Database::pdo();$a=require_auth();$s=load_profile_state($pdo,(int)$a['user']['id']);success_response(calculate_cognitive_report($s['cognitive_raw']));}
