<?php
declare(strict_types=1);
define('APP_ROOT',__DIR__);require_once APP_ROOT.'/core/response.php';$configPath=APP_ROOT.'/config.php';if(!is_file($configPath))error_response('CONFIG_MISSING','فایل config.php پیدا نشد. config.sample.php را کپی و تنظیم کنید.',500);$APP_CONFIG=require$configPath;date_default_timezone_set($APP_CONFIG['app']['timezone']??'Asia/Tehran');
foreach(['/core/db.php','/core/validate.php','/core/auth.php','/logic/scoring.php','/logic/nodes.php','/logic/progression.php','/routes/auth_routes.php','/routes/profile_routes.php','/routes/game_routes.php','/routes/leaderboard_routes.php','/routes/ai_routes.php']as$f)require_once APP_ROOT.$f;
set_exception_handler(function(Throwable$e):void{error_log('[iCompetency API] '.$e->getMessage()."\n".$e->getTraceAsString());error_response('SERVER_ERROR',(bool)app_config('app.debug',false)?$e->getMessage():'خطای داخلی سرور رخ داد.',500);});
function apply_cors_headers(array$c):void{$origin=$_SERVER['HTTP_ORIGIN']??'';$allowed=$c['app']['cors_allowed_origins']??[];if(in_array('*',$allowed,true))header('Access-Control-Allow-Origin: *');elseif($origin!==''&&in_array($origin,$allowed,true)){header('Access-Control-Allow-Origin: '.$origin);header('Vary: Origin');}header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With');header('Access-Control-Max-Age: 86400');}
function normalize_request_path():string{$uri=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$uri=str_replace('\\','/',$uri);$base=rtrim(dirname(str_replace('\\','/',$_SERVER['SCRIPT_NAME']??'')),'/');if($base!==''&&$base!=='/'&&strpos($uri,$base)===0)$uri=substr($uri,strlen($base));if(strpos($uri,'/index.php')===0)$uri=substr($uri,strlen('/index.php'))?:'/';$uri='/'.trim($uri,'/');return$uri==='/'?'/':rtrim($uri,'/');}
apply_cors_headers($APP_CONFIG);if(($_SERVER['REQUEST_METHOD']??'GET')==='OPTIONS'){http_response_code(204);exit;}$method=strtoupper($_SERVER['REQUEST_METHOD']??'GET');$path=normalize_request_path();
if($path==='/'&&$method==='GET')success_response(['name'=>'iCompetency API','version'=>'1.0.0','status'=>'ok']);if($path==='/health'&&$method==='GET'){$d=['status'=>'ok','time'=>date(DATE_ATOM)];if(isset($_GET['db'])&&$_GET['db']==='1'){Database::pdo()->query('SELECT 1');$d['database']='ok';}success_response($d);}foreach(['handle_auth_route','handle_profile_route','handle_game_route','handle_leaderboard_route','handle_ai_route']as$h)if($h($method,$path))exit;error_response('NOT_FOUND','مسیر API پیدا نشد.',404);
